/**
 * Where al-Ḥuṣarī's teaching recitation says each rule card example (spec F2): its āya and,
 * measured in the sound, where in the āya's file it starts and ends (milliseconds). Examples the
 * Qurʾān does not have as written are not here and stay silent: عَلَيْهِمْ سَلَامٌ.
 * Generated by `npm run card-audio -w @arda/tools` (tools/src/cardAudio.ts); do not edit.
 */

export interface ExampleAudio {
  /** `hafs:sura:aya:from-to`: the words the example is. */
  key: string;
  sura: number;
  aya: number;
  clip: readonly [number, number];
  /** What the reciter says, where its vowels differ from the example as the sheet writes it. */
  quran?: string;
}

export const CARD_AUDIO: Readonly<Record<string, ExampleAudio>> = {
  "مَنْ آمَنَ": {"key":"hafs:2:62:8-9","sura":2,"aya":62,"clip":[12440,14260],"quran":"مَنْ ءَامَنَ"},
  "مِنْ هَادٍ": {"key":"hafs:13:33:38-39","sura":13,"aya":33,"clip":[61040,62830]},
  "أَنْعَمْتَ": {"key":"hafs:1:7:3-3","sura":1,"aya":7,"clip":[2050,3220]},
  "عَلِيمٌ حَكِيمٌ": {"key":"hafs:4:26:13-14","sura":4,"aya":26,"clip":[18030,20860]},
  "مِنْ غَائِبَةٍ": {"key":"hafs:27:75:2-3","sura":27,"aya":75,"clip":[1060,4890]},
  "وَالْمُنْخَنِقَةُ": {"key":"hafs:5:3:12-12","sura":5,"aya":3,"clip":[14550,16910]},
  "مَنْ يَقُولُ": {"key":"hafs:2:8:3-4","sura":2,"aya":8,"clip":[2400,4370]},
  "مِنْ نُورٍ": {"key":"hafs:24:40:32-33","sura":24,"aya":40,"clip":[61710,63810]},
  "مِنْ مَاءٍ": {"key":"hafs:2:164:22-23","sura":2,"aya":164,"clip":[42310,46400]},
  "مِنْ وَالٍ": {"key":"hafs:13:11:34-35","sura":13,"aya":11,"clip":[55420,57340]},
  "مِنْ لَدُنْهُ": {"key":"hafs:4:40:12-13","sura":4,"aya":40,"clip":[20040,22030]},
  "غَفُورٌ رَحِيمٌ": {"key":"hafs:2:173:24-25","sura":2,"aya":173,"clip":[42730,45940]},
  "مِنْ بَعْدِ": {"key":"hafs:2:27:5-6","sura":2,"aya":27,"clip":[6390,8480]},
  "مِنۢ بَعْدِ": {"key":"hafs:2:27:5-6","sura":2,"aya":27,"clip":[6390,8480]},
  "سَمِيعٌ بَصِيرٌ": {"key":"hafs:22:61:14-15","sura":22,"aya":61,"clip":[23360,26360]},
  "زَوْجٍ بَهِيجٍ": {"key":"hafs:22:5:68-69","sura":22,"aya":5,"clip":[143420,146330]},
  "مِنْ تَابَ": {"key":"hafs:19:60:2-3","sura":19,"aya":60,"clip":[1370,3390],"quran":"مَن تَابَ"},
  "مِنْ ثَمَرَةٍ": {"key":"hafs:2:25:16-17","sura":2,"aya":25,"clip":[33910,36120]},
  "مَنْ جَاءَ": {"key":"hafs:6:160:1-2","sura":6,"aya":160,"clip":[30,3350]},
  "مِنْ دِيَارِهِمْ": {"key":"hafs:2:243:6-7","sura":2,"aya":243,"clip":[4880,7670]},
  "نَفْسٍ ذَائِقَةٍ": {"key":"hafs:3:185:2-3","sura":3,"aya":185,"clip":[970,5440],"quran":"نَفْسٍ ذَآئِقَةُ"},
  "مِنْكُمْ": {"key":"hafs:2:65:5-5","sura":2,"aya":65,"clip":[5220,6950]},
  "تَرْمِيهِمْ بِحِجَارَةٍ": {"key":"hafs:105:4:1-2","sura":105,"aya":4,"clip":[150,5030]},
  "لَكُمْ مَا": {"key":"hafs:2:29:4-5","sura":2,"aya":29,"clip":[3080,5010]},
  "إِنَّ": {"key":"hafs:103:2:1-1","sura":103,"aya":2,"clip":[120,2650]},
  "النَّاسِ": {"key":"hafs:114:1:4-4","sura":114,"aya":1,"clip":[3030,4880]},
  "ثُمَّ": {"key":"hafs:102:4:1-1","sura":102,"aya":4,"clip":[240,1420]},
  "عَمَّ": {"key":"hafs:78:1:1-1","sura":78,"aya":1,"clip":[360,1850]},
  "وَمَا هُمْ بِمُؤْمِنِينَ": {"key":"hafs:2:8:9-11","sura":2,"aya":8,"clip":[10330,14230]},
  "كَمْ مِنْ فِئَةٍ": {"key":"hafs:2:249:49-51","sura":2,"aya":249,"clip":[95290,99290]},
  "أَلَمْ تَرَ": {"key":"hafs:105:1:1-2","sura":105,"aya":1,"clip":[140,1490]},
  "قَدْ أَفْلَحَ": {"key":"hafs:87:14:1-2","sura":87,"aya":14,"clip":[120,1970]},
  "أَطْعَمَهُمْ": {"key":"hafs:106:4:2-2","sura":106,"aya":4,"clip":[2900,5260]},
  "الْأَبْتَرُ": {"key":"hafs:108:3:4-4","sura":108,"aya":3,"clip":[3530,5380]},
  "النَّجْدَيْنِ": {"key":"hafs:90:10:2-2","sura":90,"aya":10,"clip":[2840,5230]},
  "خَلَقْنَا": {"key":"hafs:90:4:2-2","sura":90,"aya":4,"clip":[990,2300]},
  "صِنْوَانٌ": {"key":"hafs:13:4:12-12","sura":13,"aya":4,"clip":[24960,27410],"quran":"صِنْوَانٍ"},
  "قِنْوَانٌ": {"key":"hafs:6:99:23-23","sura":6,"aya":99,"clip":[44980,47360]},
  "الدُّنْيَا": {"key":"hafs:2:85:38-38","sura":2,"aya":85,"clip":[102790,104660]},
  "بُنْيَانٌ": {"key":"hafs:37:97:4-4","sura":37,"aya":97,"clip":[2250,3970],"quran":"بُنْيَٰنًا"},
};
