"""The repository logo, docs/assets/logo.svg (docs/spec/04-design-system.md §11).

The mark beside the name "ʿArḍa" (Fraunces 600) and the Arabic name "العَرْضة" (DigitalKhatt
IndoPak), on ink. The text is outlined, so GitHub and every viewer draw it without the fonts.
Fraunces has no ʿayn (U+02BF); Amiri 700 draws it, as in the app (global.css, .logo-wordmark).

    pip install fonttools brotli uharfbuzz
    python3 apps/web/scripts/logo-svg.py      # from the repository root
"""

import io
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'docs' / 'assets' / 'logo.svg'

INK = '#10201b'
ON_INK = '#f4eee2'
SAFFRON = '#e8a93b'
TEAL = '#3fb5a3'


def node_modules(package: str) -> Path:
    """The package's folder, looked up from the repository root upwards (npm workspaces)."""
    for folder in [ROOT, *ROOT.parents]:
        candidate = folder / 'node_modules' / package
        if candidate.is_dir():
            return candidate
    raise SystemExit(f'{package} not found: run npm ci first')


FRAUNCES = node_modules('@fontsource-variable/fraunces') / 'files'
AMIRI = node_modules('@fontsource/amiri') / 'files'
FONTS = {
    # Fallback order per character, as the browser does with the fonts' unicode ranges.
    'latin': [
        (FRAUNCES / 'fraunces-latin-wght-normal.woff2', {'wght': 600}),
        (FRAUNCES / 'fraunces-latin-ext-wght-normal.woff2', {'wght': 600}),
        (AMIRI / 'amiri-latin-ext-700-normal.woff2', {}),
    ],
    'arabic': [(ROOT / 'apps/web/public/fonts/DigitalKhattIndoPak.woff2', {})],
}


class Face:
    def __init__(self, path: Path, variations: dict):
        tt = TTFont(path)
        self.cmap = tt.getBestCmap()
        tt.flavor = None  # HarfBuzz reads plain sfnt, not WOFF2
        data = io.BytesIO()
        tt.save(data)
        self.upem = tt['head'].unitsPerEm
        self.font = hb.Font(hb.Face(hb.Blob(data.getvalue())))
        if variations:
            self.font.set_variations(variations)


def runs(text: str, faces: list[Face]):
    """Split the text into runs of the first face that has each character."""
    current, start = None, 0
    for i, char in enumerate(text):
        face = next((f for f in faces if ord(char) in f.cmap), None)
        if face is None:
            raise SystemExit(f'no font has U+{ord(char):04X}')
        if current is not None and face is not current:
            yield current, text[start:i]
            start = i
        current = face
    yield current, text[start:]


def outline(text: str, faces: list[Face], size: float, rtl: bool = False):
    """The text as one SVG path at `size` px, origin on the baseline, and its bounds."""
    pen = SVGPathPen(None, ntos=lambda n: f'{n:.2f}'.rstrip('0').rstrip('.'))
    bounds = BoundsPen(None)
    x = 0.0
    for face, part in runs(text, faces):
        buf = hb.Buffer()
        buf.add_str(part)
        buf.guess_segment_properties()
        if rtl:
            buf.direction = 'rtl'
        hb.shape(face.font, buf, {'kern': True, 'liga': True})
        scale = size / face.upem
        for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
            gx = x + pos.x_offset * scale
            gy = pos.y_offset * scale
            matrix = (scale, 0, 0, -scale, gx, -gy)
            face.font.draw_glyph_with_pen(info.codepoint, TransformPen(pen, matrix))
            face.font.draw_glyph_with_pen(info.codepoint, TransformPen(bounds, matrix))
            x += pos.x_advance * scale
    return pen.getCommands(), bounds.bounds, x


def main():
    latin = [Face(p, v) for p, v in FONTS['latin']]
    arabic = [Face(p, v) for p, v in FONTS['arabic']]
    name, (nx0, ny0, nx1, ny1), _ = outline('ʿArḍa', latin, 132)
    arabic_name, (ax0, ay0, ax1, ay1), _ = outline('العَرْضة', arabic, 100, rtl=True)

    pad, mark, gap = 56, 200, 56
    # The bounds are in SVG space already (y down, the baseline at 0): the top is y0.
    name_h, arabic_h, lead = ny1 - ny0, ay1 - ay0, 36
    block = name_h + lead + arabic_h
    height = max(mark, block) + 2 * pad
    text_x = pad + mark + gap
    name_top = (height - block) / 2
    name_base = name_top - ny0
    arabic_base = name_top + name_h + lead - ay0
    width = text_x + max(nx1 - nx0, ax1 - ax0) + pad
    k = mark / 2 / 231  # the outer ring's outer edge (226 + 5) on the mark's 560 units
    cx, cy = pad + mark / 2, height / 2

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:.0f} {height:.0f}" width="{width:.0f}" height="{height:.0f}" role="img" aria-labelledby="title">
  <title id="title">ʿArḍa (العَرْضة)</title>
  <!-- Generated by apps/web/scripts/logo-svg.py: the mark (components/Logo.tsx, rings) and the outlined name. -->
  <rect width="{width:.0f}" height="{height:.0f}" rx="40" fill="{INK}"/>
  <g transform="translate({cx:.2f} {cy:.2f}) scale({k:.5f}) translate(-280 -280)" fill="none">
    <circle cx="280" cy="280" r="226" stroke="{TEAL}" stroke-width="10"/>
    <circle cx="280" cy="280" r="160" stroke="{TEAL}" stroke-width="10" opacity="0.6"/>
    <g stroke="{SAFFRON}" stroke-width="20">
      <rect x="167" y="167" width="226" height="226"/>
      <rect x="167" y="167" width="226" height="226" transform="rotate(45 280 280)"/>
    </g>
  </g>
  <path fill="{ON_INK}" transform="translate({text_x - nx0:.2f} {name_base:.2f})" d="{name}"/>
  <path fill="{SAFFRON}" transform="translate({text_x - ax0:.2f} {arabic_base:.2f})" d="{arabic_name}"/>
</svg>
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(svg, encoding='utf-8')
    print(f'{OUT.relative_to(ROOT)} ({width:.0f} × {height:.0f})')


if __name__ == '__main__':
    main()
