import { sura as suraOf } from '@arda/quran';
import type { TanzilText } from './tanzil';
import { splitWords } from './words';

/**
 * The number of words of every āya, split as the packs split them (pause signs are not words;
 * the basmala Tanzil writes before āya 1 is not part of it), so that a word number in an
 * assignment means the same word on the page. Needs no annotations.
 */
export function wordCounts(tanzil: TanzilText): number[][] {
  const counts: number[][] = [];
  for (let n = 1; n <= 114; n++) {
    const ayat: number[] = [];
    for (let aya = 1; aya <= suraOf(n)!.ayas; aya++) {
      const text = tanzil.ayat.get(`${n}:${aya}`);
      if (!text) throw new Error(`Tanzil: ${n}:${aya} is missing`);
      const words = splitWords([...text]).length;
      // al-Fātiḥa's basmala is its first āya; at-Tawba has none.
      ayat.push(aya === 1 && n !== 1 && n !== 9 ? words - 4 : words);
    }
    counts.push(ayat);
  }
  return counts;
}

/** `packages/quran/src/words.ts`, one line of numbers per sūra. */
export function countsModule(counts: readonly (readonly number[])[]): string {
  const lines = counts.map((ayat) => `  '${ayat.join(' ')}',`);
  return `/**
 * Words per āya (Ḥafṣ), one string per sūra, as the content packs split Tanzil's Uthmani text
 * 1.1 (pause signs are not words; the basmala before āya 1 is not part of it). Generated by
 * \`npm run counts -w @arda/tools\`; do not edit.
 */
const COUNTS: readonly string[] = [
${lines.join('\n')}
];

const parsed = COUNTS.map((line) => line.split(' ').map(Number));

/** The number of words of an āya, or undefined when there is no such āya. */
export function wordCount(sura: number, aya: number): number | undefined {
  return parsed[sura - 1]?.[aya - 1];
}
`;
}
