/**
 * The Madīna muṣḥaf's pages (604, the King Fahd Complex 15-line print) as Tanzil's Quran
 * Metadata 1.0 lists them: the āya each page starts with. Written to
 * `packages/quran/src/pages.ts` by `npm run pages -w @arda/tools`.
 */
export function madinaPageStarts(metadata: string): [number, number][] {
  const block = /QuranData\.Page = \[([\s\S]*?)\];/.exec(metadata);
  if (!block) throw new Error('Tanzil metadata: no page list');
  const starts = [...block[1]!.matchAll(/\[(\d+), (\d+)\]/g)].map(
    (m) => [Number(m[1]), Number(m[2])] as [number, number]
  );
  // The list ends with a sentinel after the last page (sūra 115).
  if (starts.at(-1)?.[0] !== 115 || starts.length !== 605) {
    throw new Error(`Tanzil metadata: ${starts.length} page entries`);
  }
  return starts.slice(0, -1);
}

export function pagesModule(starts: readonly [number, number][]): string {
  const rows: string[] = [];
  for (let i = 0; i < starts.length; i += 10) {
    rows.push(
      `  '${starts
        .slice(i, i + 10)
        .map(([s, a]) => `${s}:${a}`)
        .join(' ')}',`
    );
  }
  return `/**
 * Where each page of the Madīna muṣḥaf (604 pages, 15 lines) starts: the first āya on it, ten
 * pages per string, from Tanzil's Quran Metadata 1.0 (© 2008–2009 Tanzil.info, CC BY 3.0,
 * https://tanzil.net/docs/quran_metadata). Generated by \`npm run pages -w @arda/tools\`; do not
 * edit.
 */
const ROWS: readonly string[] = [
${rows.join('\n')}
];

const STARTS = ROWS.flatMap((row) =>
  row.split(' ').map((key) => key.split(':').map(Number) as [number, number])
);

/** Pages of the Madīna muṣḥaf. */
export const MADINA_PAGES = STARTS.length;

const before = (a: readonly [number, number], b: readonly [number, number]) =>
  a[0] < b[0] || (a[0] === b[0] && a[1] < b[1]);

/** The Madīna page an āya is on (every page there starts with a new āya). */
export function madinaPage(sura: number, aya: number): number {
  let lo = 0;
  let hi = STARTS.length - 1;
  while (lo < hi) {
    const mid = Math.ceil((lo + hi) / 2);
    if (before([sura, aya], STARTS[mid]!)) hi = mid - 1;
    else lo = mid;
  }
  return lo + 1;
}

/** The first āya on a Madīna page, or undefined when there is no such page. */
export function madinaPageStart(page: number): [sura: number, aya: number] | undefined {
  return STARTS[page - 1];
}
`;
}
