/**
 * The lab's sets of letters, in the order they are taught: first the three whistling letters
 * and rāʾ (owner, 2026-10-06), then the six of the throat, from the deepest out (2026-10-07).
 */
export const LAB_SETS = {
  first: ['sin', 'zay', 'sad', 'ra'],
  throat: ['hamza', 'ha', 'ayn', 'hha', 'ghayn', 'kha'],
} as const;
export type LabSet = keyof typeof LAB_SETS;

export const LAB_LETTERS = [...LAB_SETS.first, ...LAB_SETS.throat] as const;
export type LabLetterId = (typeof LAB_LETTERS)[number];
/** The letters a listening quiz can answer with: every letter of the lab but rāʾ. */
export type HeardId = Exclude<LabLetterId, 'ra'>;

/** Rāʾ with fatḥa or ḍamma is heavy (tafkhīm), with kasra light (tarqīq). */
export type Weight = 'heavy' | 'light';

/** A word of the lab, from the packs (`words.ts` is generated by tools/src/lab.ts). */
export interface LabWord {
  /** `hafs:sura:aya:n`, timed as a word of its own in al-Ḥuṣarī's teaching recitation. */
  key: string;
  letter: LabLetterId;
  /** Rāʾ only: heavy or light, read from its vowel. */
  weight?: Weight;
  uthmani: string;
  indopak: string;
  /** The letter the word is about, as UTF-16 offsets into the text of each script. */
  focus: { uthmani: readonly [number, number]; indopak: readonly [number, number] };
  /**
   * Where the word sounds in its āya's file, in milliseconds, measured in the sound
   * (tools/src/labClips.ts): the timings start at the first vowel and cut a sīn's hiss.
   */
  clip: readonly [number, number];
}

/** Two words to hear one after the other: one letter differs (exact) or more (near). */
export interface LabPair {
  letters: readonly [LabLetterId, LabLetterId];
  exact: boolean;
  words: readonly [LabWord, LabWord];
}
