/**
 * The letter lab's words (spec F5): real words from the shipped packs, each timed as a word of
 * its own in al-Ḥuṣarī's teaching recitation, with where it really sounds (tools/lab-clips.json).
 * Generated by `npm run lab -w @arda/tools` from the picks in tools/src/lab.ts; do not edit.
 */
import type { LabPair, LabWord } from './types';

export const LAB_WORDS: readonly LabWord[] = [
  {"key":"hafs:87:1:1","letter":"sin","uthmani":"سَبِّحِ","indopak":"سَبِّحِ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[110,1300]},
  {"key":"hafs:97:5:1","letter":"sin","uthmani":"سَلَٰمٌ","indopak":"سَلٰمٌ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[340,1880]},
  {"key":"hafs:102:3:2","letter":"sin","uthmani":"سَوْفَ","indopak":"سَوْفَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1340,2410]},
  {"key":"hafs:93:2:3","letter":"sin","uthmani":"سَجَىٰ","indopak":"سَجٰي","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2460,3910]},
  {"key":"hafs:78:13:2","letter":"sin","uthmani":"سِرَاجًا","indopak":"سِرَاجًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1760,3960]},
  {"key":"hafs:105:4:4","letter":"sin","uthmani":"سِجِّيلٍ","indopak":"سِجِّيْلٍ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[5750,7680]},
  {"key":"hafs:81:8:3","letter":"sin","uthmani":"سُئِلَتْ","indopak":"سُىِٕلَتْ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2610,4040]},
  {"key":"hafs:2:32:2","letter":"sin","uthmani":"سُبْحَٰنَكَ","indopak":"سُبْحٰنَكَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1590,3510]},
  {"key":"hafs:2:93:13","letter":"sin","uthmani":"سَمِعْنَا","indopak":"سَمِعْنَا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[35090,36780]},
  {"key":"hafs:2:154:6","letter":"sin","uthmani":"سَبِيلِ","indopak":"سَبِيْلِ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[5810,7270]},
  {"key":"hafs:99:1:2","letter":"zay","uthmani":"زُلْزِلَتِ","indopak":"زُلْزِلَتِ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1180,2770]},
  {"key":"hafs:102:2:2","letter":"zay","uthmani":"زُرْتُمُ","indopak":"زُرْتُمُ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1590,2810]},
  {"key":"hafs:79:13:3","letter":"zay","uthmani":"زَجْرَةٌ","indopak":"زَجْرَةٌ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2720,4760]},
  {"key":"hafs:81:7:3","letter":"zay","uthmani":"زُوِّجَتْ","indopak":"زُوِّجَتْ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2340,4000]},
  {"key":"hafs:91:9:4","letter":"zay","uthmani":"زَكَّىٰهَا","indopak":"زَكّٰىهَا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2610,4950]},
  {"key":"hafs:95:1:2","letter":"zay","uthmani":"وَٱلزَّيْتُونِ","indopak":"وَالزَّيْتُوْنِ","focus":{"uthmani":[4,7],"indopak":[4,7]},"clip":[1820,4060]},
  {"key":"hafs:98:5:13","letter":"zay","uthmani":"ٱلزَّكَوٰةَ","indopak":"الزَّكٰوةَ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[23190,25210]},
  {"key":"hafs:2:212:1","letter":"zay","uthmani":"زُيِّنَ","indopak":"زُيِّنَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[200,1470]},
  {"key":"hafs:2:230:10","letter":"zay","uthmani":"زَوْجًا","indopak":"زَوْجًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[11490,12720]},
  {"key":"hafs:2:10:4","letter":"zay","uthmani":"فَزَادَهُمُ","indopak":"فَزَادَهُمُ","focus":{"uthmani":[2,4],"indopak":[2,4]},"clip":[4240,6050]},
  {"key":"hafs:1:6:2","letter":"sad","uthmani":"ٱلصِّرَٰطَ","indopak":"الصِّرَاطَ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[760,2000]},
  {"key":"hafs:78:38:5","letter":"sad","uthmani":"صَفًّا","indopak":"صَفًّا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[7350,8960]},
  {"key":"hafs:80:25:4","letter":"sad","uthmani":"صَبًّا","indopak":"صَبًّا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[5300,6860]},
  {"key":"hafs:87:19:1","letter":"sad","uthmani":"صُحُفِ","indopak":"صُحُفِ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[70,1030]},
  {"key":"hafs:81:18:1","letter":"sad","uthmani":"وَٱلصُّبْحِ","indopak":"وَالصُّبْحِ","focus":{"uthmani":[4,7],"indopak":[4,7]},"clip":[30,1590]},
  {"key":"hafs:89:13:1","letter":"sad","uthmani":"فَصَبَّ","indopak":"فَصَبَّ","focus":{"uthmani":[2,4],"indopak":[2,4]},"clip":[160,1300]},
  {"key":"hafs:2:3:5","letter":"sad","uthmani":"ٱلصَّلَوٰةَ","indopak":"الصَّلٰوةَ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[5020,6510]},
  {"key":"hafs:2:158:2","letter":"sad","uthmani":"ٱلصَّفَا","indopak":"الصَّفَا","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[1150,2570]},
  {"key":"hafs:2:250:9","letter":"sad","uthmani":"صَبْرًا","indopak":"صَبْرًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[14800,16840]},
  {"key":"hafs:2:138:1","letter":"sad","uthmani":"صِبْغَةَ","indopak":"صِبْغَةَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[570,1860]},
  {"key":"hafs:1:2:3","letter":"ra","uthmani":"رَبِّ","indopak":"رَبِّ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1930,2720],"weight":"heavy"},
  {"key":"hafs:1:1:3","letter":"ra","uthmani":"ٱلرَّحْمَٰنِ","indopak":"الرَّحْمٰنِ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[1500,2850],"weight":"heavy"},
  {"key":"hafs:98:2:1","letter":"ra","uthmani":"رَسُولٌ","indopak":"رَسُوْلٌ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[240,2240],"weight":"heavy"},
  {"key":"hafs:88:18:4","letter":"ra","uthmani":"رُفِعَتْ","indopak":"رُفِعَتْ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[4700,6300],"weight":"heavy"},
  {"key":"hafs:78:38:3","letter":"ra","uthmani":"ٱلرُّوحُ","indopak":"الرُّوْحُ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[2580,3770],"weight":"heavy"},
  {"key":"hafs:90:13:2","letter":"ra","uthmani":"رَقَبَةٍ","indopak":"رَقَبَةٍ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1190,2610],"weight":"heavy"},
  {"key":"hafs:2:185:2","letter":"ra","uthmani":"رَمَضَانَ","indopak":"رَمَضَانَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[1040,2590],"weight":"heavy"},
  {"key":"hafs:2:22:16","letter":"ra","uthmani":"رِزْقًا","indopak":"رِزْقًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[30440,31400],"weight":"light"},
  {"key":"hafs:2:59:13","letter":"ra","uthmani":"رِجْزًا","indopak":"رِجْزًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[20070,20990],"weight":"light"},
  {"key":"hafs:2:164:35","letter":"ra","uthmani":"ٱلرِّيَٰحِ","indopak":"الرِّيٰحِ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[69060,70910],"weight":"light"},
  {"key":"hafs:2:177:31","letter":"ra","uthmani":"ٱلرِّقَابِ","indopak":"الرِّقَابِ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[72450,74130],"weight":"light"},
  {"key":"hafs:89:16:7","letter":"ra","uthmani":"رِزْقَهُۥ","indopak":"رِزْقَهٗ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[8040,9460],"weight":"light"},
  {"key":"hafs:106:2:2","letter":"ra","uthmani":"رِحْلَةَ","indopak":"رِحْلَةَ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2610,3900],"weight":"light"},
  {"key":"hafs:2:239:3","letter":"ra","uthmani":"فَرِجَالًا","indopak":"فَرِجَالًا","focus":{"uthmani":[2,4],"indopak":[2,4]},"clip":[2220,4340],"weight":"light"},
];

export const LAB_PAIRS: readonly LabPair[] = [
  {"letters":["sin","sad"],"exact":true,"words":[{"key":"hafs:2:216:7","letter":"sin","uthmani":"وَعَسَىٰٓ","indopak":"وَعَسٰٓي","focus":{"uthmani":[4,6],"indopak":[4,7]},"clip":[11140,13710]},{"key":"hafs:79:21:2","letter":"sad","uthmani":"وَعَصَىٰ","indopak":"وَعَصٰي","focus":{"uthmani":[4,6],"indopak":[4,6]},"clip":[1510,3260]}]},
  {"letters":["sin","sad"],"exact":false,"words":[{"key":"hafs:2:185:35","letter":"sin","uthmani":"ٱلْعُسْرَ","indopak":"الْعُسْرَ","focus":{"uthmani":[5,7],"indopak":[5,7]},"clip":[74900,76220]},{"key":"hafs:103:1:1","letter":"sad","uthmani":"وَٱلْعَصْرِ","indopak":"وَالْعَصْرِ","focus":{"uthmani":[7,9],"indopak":[7,9]},"clip":[110,2070]}]},
  {"letters":["sin","sad"],"exact":false,"words":[{"key":"hafs:79:3:2","letter":"sin","uthmani":"سَبْحًا","indopak":"سَبْحًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2580,3980]},{"key":"hafs:100:3:2","letter":"sad","uthmani":"صُبْحًا","indopak":"صُبْحًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[2630,4040]}]},
  {"letters":["sin","sad"],"exact":false,"words":[{"key":"hafs:2:184:9","letter":"sin","uthmani":"سَفَرٍ","indopak":"سَفَرٍ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[16610,18280]},{"key":"hafs:2:69:14","letter":"sad","uthmani":"صَفْرَآءُ","indopak":"صَفْرَا࢜ءُ","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[19850,22210]}]},
  {"letters":["sin","zay"],"exact":false,"words":[{"key":"hafs:78:20:4","letter":"sin","uthmani":"سَرَابًا","indopak":"سَرَابًا","focus":{"uthmani":[0,2],"indopak":[0,2]},"clip":[5100,6940]},{"key":"hafs:88:16:1","letter":"zay","uthmani":"وَزَرَابِىُّ","indopak":"وَّزَرَابِيُّ","focus":{"uthmani":[2,4],"indopak":[3,5]},"clip":[380,2760]}]},
  {"letters":["sin","zay"],"exact":false,"words":[{"key":"hafs:2:273:20","letter":"sin","uthmani":"يَسْـَٔلُونَ","indopak":"يَسْـٔ͏َلُوْنَ","focus":{"uthmani":[2,4],"indopak":[2,4]},"clip":[49750,51880]},{"key":"hafs:2:217:30","letter":"zay","uthmani":"يَزَالُونَ","indopak":"يَزَالُوْنَ","focus":{"uthmani":[2,4],"indopak":[2,4]},"clip":[57900,59900]}]},
  {"letters":["sin","zay"],"exact":false,"words":[{"key":"hafs:2:205:10","letter":"sin","uthmani":"وَٱلنَّسْلَ","indopak":"وَالنَّسْلَ","focus":{"uthmani":[7,9],"indopak":[7,9]},"clip":[11350,13510]},{"key":"hafs:2:176:4","letter":"zay","uthmani":"نَزَّلَ","indopak":"نَزَّلَ","focus":{"uthmani":[2,5],"indopak":[2,5]},"clip":[4620,5820]}]},
];
